#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  "(1) web" 2 3 4 5 6 7 8 9 10
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        time


# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.5
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_placement      exterior
yabai -m config window_border_width          2
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_color   0xffFF8500
yabai -m config normal_window_border_color   0x00505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config split_ratio                  0.60
yabai -m config auto_balance                 off
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# Space labels
yabai -m space 1 --label "Primary"
yabai -m space 2 --label "Comms"
yabai -m space 3 --label "Tools"
yabai -m space 4 --label "Media"
yabai -m space 5 --label "Social"
yabai -m space 6 --label "Float"
yabai -m space 7 --label "Secondary"

# Space config
# yabai -m config --space 6 layout float

# Don't manage
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^App Store$"          manage=off
yabai -m rule --add app="^Activity Monitor$"   manage=off
yabai -m rule --add app="^Preview$"            manage=off
yabai -m rule --add app="^zoom.us$"            manage=off
yabai -m rule --add app="^Spotify$"            manage=off
yabai -m rule --add app="^Simulator$"            manage=off

# Primary
# yabai -m rule --add app="iTerm2"               space=1
# yabai -m rule --add app="Chrome"               space=1
# yabai -m rule --add app="Xcode"                space=1

# # Communication
# yabai -m rule --add app="Slack"                space=2
# yabai -m rule --add app="Messages"             space=2

# # Tools
# yabai -m rule --add app="Notion"               space=3

# # Media
# yabai -m rule --add app="Spotify"              space=4

# # Social
# yabai -m rule --add app="Slack"                 space=5
